version: '3'
services:
  server:
    build: ./api-server
    environment:
      - NODE_ENV=dev
      - ENV_PATH=.env
    command: adonis serve --dev
    tty: true
    working_dir: /usr/src/app
    volumes:
      - ./api-server:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - 3333:3333
    container_name: weight-rank-api
    depends_on:
      - db_mysql
  db_mysql:
    image: mysql:8.0
    restart: always
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./db/.dev.env
    expose:
      - 3307
    ports:
      - 3307:3307
    volumes:
      - ./db/data/mysql:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    container_name: mysql_db
  db_redis:
    image: redis:6.2-alpine
    command: --port 7001
    ports:
      - 7001:7001
    volumes:
      - ./db/data/redis:/var/lib/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
    container_name: redis_cache
